### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by cesarferreira** [ravidsrk/generator-android-boilerplate#1]
```bash
✝  ~/Downloads/ribot  yo android-boilerplate

     _-----_     ╭──────────────────────────╮
    |       |    │    Welcome to the rad    │
    |--(o)--|    │    Android Boilerplate   │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What are you calling your app? (ribot)

events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (/usr/local/lib/node_modules/generator-android-boilerplate/node_modules/yeoman-generator/lib/base.js:240:45)
    at module.exports.yeoman.Base.extend.prompting (/usr/local/lib/node_modules/generator-android-boilerplate/generators/app/index.js:53:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-android-boilerplate/node_modules/yeoman-generator/lib/base.js:439:23)
    at /usr/local/lib/node_modules/generator-android-boilerplate/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-android-boilerplate/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-android-boilerplate/node_modules/yeoman-generator/lib/base.js:440:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by ravidsrk** [comment]
Which version of node.js you are using? Make sure you are using generator-android-boilerplate@0.1.6. 
Here is what i got.

`➜  ribot yo android-boilerplate

     _-----_     ╭──────────────────────────╮
    |       |    │    Welcome to the rad    │
    |--(o)--|    │    Android Boilerplate   │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What are you calling your app? ribot
? What package will you be publishing the app under? in.boilerplate.sample
? What Android SDK will you be targeting? 23
? What is the minimum Android SDK you wish to support? 15
   create gradle/wrapper/gradle-wrapper.jar
   create gradle/wrapper/gradle-wrapper.properties
   create config/quality/checkstyle/checkstyle-config.xml
   create config/quality/findbugs/android-exclude-filter.xml
   create config/quality/pmd/pmd-ruleset.xml
   create config/quality/quality.gradle
   create images/check-task-diagram.png
   create app/keystore/debug.keystore
   create .gitignore
   create build.gradle
   create gradle.properties
   create gradlew
   create gradlew.bat
   create settings.gradle
   create app/.gitignore
   create app/proguard-rules.pro
   create README.md
   create app/build.gradle
   create app/src/androidTest/java/in/boilerplate/sample/MainActivityTest.java
   create app/src/androidTest/java/in/boilerplate/sample/runner/RxAndroidJUnitRunner.java
   create app/src/androidTest/java/in/boilerplate/sample/runner/UnlockDeviceAndroidJUnitRunner.java
   create app/src/androidTest/java/in/boilerplate/sample/util/RxIdlingExecutionHook.java
   create app/src/androidTest/java/in/boilerplate/sample/util/RxIdlingResource.java
   create app/src/commonTest/java/in/boilerplate/sample/test/common/injection/component/TestComponent.java
   create app/src/commonTest/java/in/boilerplate/sample/test/common/injection/module/ApplicationTestModule.java
   create app/src/commonTest/java/in/boilerplate/sample/test/common/TestComponentRule.java
   create app/src/commonTest/java/in/boilerplate/sample/test/common/TestDataFactory.java
   create app/src/debug/AndroidManifest.xml
   create app/src/main/AndroidManifest.xml
   create app/src/main/java/in/boilerplate/sample/BoilerplateApplication.java
   create app/src/main/java/in/boilerplate/sample/data/DataManager.java
   create app/src/main/java/in/boilerplate/sample/data/local/DatabaseHelper.java
   create app/src/main/java/in/boilerplate/sample/data/local/Db.java
   create app/src/main/java/in/boilerplate/sample/data/local/DbOpenHelper.java
   create app/src/main/java/in/boilerplate/sample/data/local/PreferencesHelper.java
   create app/src/main/java/in/boilerplate/sample/data/model/Name.java
   create app/src/main/java/in/boilerplate/sample/data/model/Profile.java
   create app/src/main/java/in/boilerplate/sample/data/model/Ribot.java
   create app/src/main/java/in/boilerplate/sample/data/remote/RibotsService.java
   create app/src/main/java/in/boilerplate/sample/data/SyncService.java
   create app/src/main/java/in/boilerplate/sample/injection/ActivityContext.java
   create app/src/main/java/in/boilerplate/sample/injection/ApplicationContext.java
   create app/src/main/java/in/boilerplate/sample/injection/component/ActivityComponent.java
   create app/src/main/java/in/boilerplate/sample/injection/component/ApplicationComponent.java
   create app/src/main/java/in/boilerplate/sample/injection/component/ConfigPersistentComponent.java
   create app/src/main/java/in/boilerplate/sample/injection/ConfigPersistent.java
   create app/src/main/java/in/boilerplate/sample/injection/module/ActivityModule.java
   create app/src/main/java/in/boilerplate/sample/injection/module/ApplicationModule.java
   create app/src/main/java/in/boilerplate/sample/injection/PerActivity.java
   create app/src/main/java/in/boilerplate/sample/ui/base/BaseActivity.java
   create app/src/main/java/in/boilerplate/sample/ui/base/BasePresenter.java
   create app/src/main/java/in/boilerplate/sample/ui/base/MvpView.java
   create app/src/main/java/in/boilerplate/sample/ui/base/Presenter.java
   create app/src/main/java/in/boilerplate/sample/ui/main/MainActivity.java
   create app/src/main/java/in/boilerplate/sample/ui/main/MainMvpView.java
   create app/src/main/java/in/boilerplate/sample/ui/main/MainPresenter.java
   create app/src/main/java/in/boilerplate/sample/ui/main/RibotsAdapter.java
   create app/src/main/java/in/boilerplate/sample/util/AndroidComponentUtil.java
   create app/src/main/java/in/boilerplate/sample/util/DialogFactory.java
   create app/src/main/java/in/boilerplate/sample/util/NetworkUtil.java
   create app/src/main/java/in/boilerplate/sample/util/RxEventBus.java
   create app/src/main/java/in/boilerplate/sample/util/RxUtil.java
   create app/src/main/java/in/boilerplate/sample/util/ViewUtil.java
   create app/src/main/res/layout/activity_main.xml
   create app/src/main/res/layout/item_ribot.xml
   create app/src/main/res/menu/menu_main.xml
   create app/src/main/res/mipmap-hdpi/ic_launcher.png
   create app/src/main/res/mipmap-mdpi/ic_launcher.png
   create app/src/main/res/mipmap-xhdpi/ic_launcher.png
   create app/src/main/res/mipmap-xxhdpi/ic_launcher.png
   create app/src/main/res/values-w820dp/dimens.xml
   create app/src/main/res/values/colors.xml
   create app/src/main/res/values/dimens.xml
   create app/src/main/res/values/strings.xml
   create app/src/main/res/values/styles.xml
   create app/src/test/java/in/boilerplate/sample/DatabaseHelperTest.java
   create app/src/test/java/in/boilerplate/sample/DataManagerTest.java
   create app/src/test/java/in/boilerplate/sample/MainPresenterTest.java
   create app/src/test/java/in/boilerplate/sample/util/DefaultConfig.java
   create app/src/test/java/in/boilerplate/sample/util/RxEventBusTest.java
   create app/src/test/java/in/boilerplate/sample/util/RxSchedulersOverrideRule.java
➜  ribot`

**Comment by cesarferreira** [comment]
> ~/Downloads/ribot  node -v

v6.2.2


> npm install -g generator-android-boilerplate

(node:43215) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
/usr/local/lib
└── generator-android-boilerplate@0.1.6

**Comment by ravidsrk** [comment]
I am using
```bash
➜  generator-android-boilerplate git:(master) node -v
v6.3.1
```
Let me test the module with v6.2.2.

**Comment by ravidsrk** [comment]
It does work with v6.2.2. 

Can you try
```bash
$ npm clean cache
$ npm install -g generator-android-boilerplate
```

**Comment by cesarferreira** [comment]
Still get the same error :/

**Comment by ravidsrk** [comment]
Can you update to latest version of yeomon and test it once?

Also can you try this?
https://github.com/ravidsrk/generator-android-mvp-starter

**Comment by ravidsrk** [comment]
@cesarferreira I have released new version with more fixes.
Here is my envinorment
```bash
➜  generator-android-boilerplate git:(master) node -v
v6.3.1
➜  generator-android-boilerplate git:(master) npm -v
3.10.5
➜  generator-android-boilerplate git:(master) yo --version
1.8.4
➜  generator-android-boilerplate git:(master) npm install -g generator-android-boilerplate
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
/usr/local/lib
└── generator-android-boilerplate@1.0.0
```
